language: haskell
ghc:
  - 7.6
env:
  - LLVM_VERSION=2.8
  - LLVM_VERSION=2.9
  - LLVM_VERSION=3.0
  - LLVM_VERSION=3.1
  - LLVM_VERSION=3.2
  - LLVM_VERSION=3.3
  - LLVM_VERSION=3.4
#  - LLVM_VERSION=3.5
install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install llvm-${LLVM_VERSION}-dev
  - cabal install haskell-src filepath cpphs
  - cabal install --only-dependencies
script:
  - ghc --make Setup.hs -o ./setup
  - ./setup configure --user --enable-tests --with-llvm-config=llvm-config-${LLVM_VERSION}
  - ./setup build
  - ./setup test