language: haskell
ghc:
  - 7.4
  - 7.6
env:
  - LLVM_VERSION=2.8
  - LLVM_VERSION=2.9
  - LLVM_VERSION=3.0
  - LLVM_VERSION=3.1
install:
  - sudo apt-get install llvm-${LLVM_VERSION}-dev
  - cabal install haskell-src filepath cpphs
  - cabal install --only-dependencies
script:
  - ghc --make Setup.hs -o ./setup
  - ./setup configure --user --with-llvm-config=llvm-config-${LLVM_VERSION}
  - ./setup Setup.hs build